# Managed by Hydra

defaults:
  - base

log:
  WandbLogger:
    project: Stance
    name: ${model.model.experiment_name}
  TensorBoardLogger:
    name: Stance

trainer:
  max_epochs: 512

model:
  module: Stance
  experiment_name: run_1

  prepare_epochs: 1

  loss_weight: [1, 1, 1, 1, 1, 1]

  point_aggr_radius: 0.03
  cluster_shift_meanActive: 300

  cal_iou_based_on_mask_start_epoch: 200

  use_mask_filter_score_feature_start_epoch: 200
  mask_filter_score_feature_thre: 0.5

  using_set_aggr_in_training: False
  using_set_aggr_in_testing: True

  max_proposal_num: 200


  test:
    TEST_NMS_THRESH: 0.3
    TEST_SCORE_THRESH: 0.09
    TEST_NPOINT_THRESH: 100
    test_mask_score_thre: -0.5
