# Managed by Hydra

defaults:
  - base

log:
  WandbLogger:
    project: Stance
    name: ${model.model.experiment_name}
  TensorBoardLogger:
    name: Stance

trainer:
  max_epochs: 512

model:
  module: Stance
  experiment_name: only_cnn_last_lstm_run1

  prepare_epochs: 1
  use_external_feature: False
  use_statistical_feature: False
  use_cnn_lstm: True

  using_set_aggr_in_training: False
  using_set_aggr_in_testing: True

  max_proposal_num: 200
